### ISSUE TITLE
[version 0.9] Export to Mongo Schema

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/mongo-modeler#100]
For this issue:

@manudous an Joaquin can give you more background about mongo Schemas

And the approach will be similar to Manfred Export using an EJS template, we will take it easy, just a single EJS Schema

Under export pod we will creatre a mongo-schema folder

The goal is to understand the task, define it in detail and pass it to a given student or students

Let's talk about this, this morning

**Comment by JTrillo** [comment]
Solved here: #304
