### ISSUE TITLE
canvas.pod updateTablePosition refactor

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/mongo-modeler#6]
UpdateTablePosition needs some refactor:
 
- Too much parameters:
  - Let's create a interface called Coordinate that will be placed under core/model
```ts
interface Coordinate {
  x: number
  y: number;
}

```
- Let's change the signature of this function to:

```diff
  const updateTablePosition = (
    id: string,
-    newX: number,
-   newY: number,
+  position: Coordinate;
    totalHeight: number
  ) => {
```

- There are harcoded numbers in the calculation:
  - Change the _1200_ to canvas size width.
  - Change the 800 to canvas size height.
  - About the _300_ add a TODO comment, that's the width of the table and we will have to treat this in a separate case (is more complex).

- Create a _canvas.business.ts_  we are going to enclose the schema update in a business method and add unit tests

The method would be something like

_canvas.business.ts_

```ts 
interface UpdateInfo {
  id : GUID;
  position: Coordinate;
  totalHeight : number;
}

const updateTablePosition = (schema : DatabaseSchema, updateInfo : UpdateInfo) => {
 // (...)
}
```

Y como quedaría en _canvas.pod.tsx_

```tsx
  const updateTablePosition = (
    id: string,
    position: Coordinate;
    totalHeight: number
  ) => {
   setSchema((prevSchema) => updateTablePosition(prevSchema, {id,position, totalHeight}));
}
```

**Comment by deletidev** [comment]
We already have Coords in canvas.vm, do I have to change Coords to Cordinate in core/module or do I leave Coords and don't create Cordinate?

**Comment by brauliodiez** [comment]
This coords let's move it to:

_./core/model/index.ts_

And let's use it everywhere
